---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: flux-system
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: 0.26.0
  interval: 10m0s
  values:
    config:
      receivers:
        oltp: null
        prometheus: null
        zipkin: null
      service:
        pipelines:
          traces:
            receivers:
              - jaeger
          metrics: null
          logs: null