---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  targetNamespace: team-badger
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 10m0s
  values:
    podLabels:
      generalized_service_type: application
      generalized_service: podinfo
    serviceMonitor:
      enabled: true



