
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  dependsOn:
  - name: otel-ingester
  interval: 10m0s
  path: ./releases/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
