kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: obs
agents: 3
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6550"
ports:
- port: 8081:80
  nodeFilters:
  - loadbalancer
- port: 443:443
  nodeFilters:
  - loadbalancer
options:
  k3d:
    wait: true
    timeout: 6m0s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  k3s:
    extraArgs:
    - arg: --tls-san=127.0.0.1
      nodeFilters:
      - server:*
    nodeLabels: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
