---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  targetNamespace: tracing
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 1.3.1
  interval: 10m0s
  values:
    podLabels:
      generalized_service_type: telemetry
      generalized_service: tempo
    serviceMonitor:
      enabled: true



