---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  targetNamespace: traces
  chart:
    spec:
      chart: tempo
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 1.21.0
  interval: 10m0s
  values:
    fullnameOverride: tempo
    podLabels:
      service_category: telemetry
      signal_type: traces
      criticality: mid
    serviceMonitor:
      enabled: true



