---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    grafana:
      enabled: true
      replicas: 1
      image:
        repository: grafana/grafana
        tag: 9.0.2
      persistence:
        enabled: true
        type: statefulset
        size: 30Gi
        storageClassName: local-path
        accessMode: ["ReadWriteOnce"]
  interval: 10m0s
  targetNamespace: monitoring

