---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  targetNamespace: storage
  values:
    fullnameOverride: minio-operator
  interval: 10m
  timeout: 2m
  chart:
    spec:
      chart: minio-operator
      version: '0.1.7'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system