---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  targetNamespace: storage
  chart:
    spec:
      chart: minio-operator
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 0.1.7
  interval: 10m0s
  values:
    fullnameOverride: minio-operator


