
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-ingester
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 10m0s
  path: ./releases/otel-ingester
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

