---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-seeder
  namespace: flux-system
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: 0.43.2
  interval: 10m0s
  values:
    mode: deployment
    fullnameOverride: "otel-seeder"
    config:
      receivers:
        kafka:
          brokers:
            - kafka-kafka-brokers.queuing.svc:9092
          topic: spans
          protocol_version: 3.3.0

      processors:
        batch:
          send_batch_size: 10000
          timeout: 10s

      exporters:
        logging:
          logLevel: debug
        otlp:
          endpoint: tracing-tempo.tracing.svc:4317
          tls:
            insecure: true

      service:
        pipelines:
          traces:
            receivers:
              - kafka
            processors:
              - batch
            exporters:
              - logging
              - otlp
          metrics: null
          logs: null