
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: otel-weeder
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./releases/otel-weeder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
