apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kube-prometheus-stack/ks.yaml
- ./kafka/ks.yaml
- ./tempo/ks.yaml
- ./otel-weeder/ks.yaml
- ./loki/ks.yaml
- ./goldilocks/ks.yaml
- ./otel-seeder/ks.yaml