apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./kube-prometheus-stack/ks.yaml
- ./cert-manager/cert-manager.yaml
- ./kafka/ks.yaml
- ./tempo/ks.yaml
- ./otel-ingester/ks.yaml
- ./loki/ks.yaml
- ./goldilocks/ks.yaml
# - ./otel-distributor/ks.yaml
# - ./otel-processor/ks.yaml
# - ./podinfo/ks.yaml
# - ./k6-trace-test/ks.yaml
