---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: flux-system
spec:
  targetNamespace: resource-audit
  chart:
    spec:
      chart: goldilocks
      sourceRef:
        kind: HelmRepository
        name: fairwinds
      version: 6.1.3
  interval: 10m0s
  values:
    controller:
      deployment:
	additionalLabels:
	  spog_service_type: observability
          spog_service: goldilocks
    vpa:
      enabled: true
