---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-processor
  namespace: flux-system
spec:
  targetNamespace: trace-pipeline
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: 0.59.1
  interval: 10m0s
  values:
    mode: deployment
    fullnameOverride: "otel-processor"
    replicaCount: 2
    serviceMonitor:
      enabled: true
      metricsEndpoints:
        - port: metrics
          path: /metrics
          scheme: http
          interval: 20s
    ports:
      metrics:
        enabled: true

    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: ${MY_POD_IP}:4320

      processors:
        batch:
          send_batch_size: 2048
          timeout: 1s
        memory_limiter:
          check_interval: 1s
          limit_percentage: 80
          spike_limit_percentage: 10
        tail_sampling:
          decision_wait: 10s
          num_traces: 100
          expected_new_traces_per_sec: 10
          policies:
            [
              {
                name: errors-policy,
                type: and,
                and: {
                  and_sub_policy:
                    [
                      {
                        name: errors-and-policy-1,
                        type: status_code,
                        status_code: { status_codes: [ ERROR ] }
                      },
                      {
                        name: errors-and-policy-2,
                        type: rate_limiting,
                        rate_limiting: { spans_per_second: 100 }
                      },
                    ]
                }
              },
              {
                name: latency-policy,
                type: latency,
                latency: {threshold_ms: 2000}
              },
              {
                name: randomized-policy,
                type: probabilistic,
                probabilistic: { sampling_percentage: 50 }
              },
            ]

      exporters:
        logging:
          verbosity: detailed
          sampling_initial: 5
          sampling_thereafter: 20
        otlp:
          endpoint: tracing-tempo.tracing.svc:4317
          tls:
            insecure: true

      service:
        pipelines:
          traces:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
              - tail_sampling
            exporters:
              - logging
              - otlp
          metrics: null
          logs: null