---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-distributor
  namespace: flux-system
spec:
  targetNamespace: trace-pipeline
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: 0.59.1
  interval: 10m0s
  values:
    mode: deployment
    fullnameOverride: "otel-distributor"
    replicaCount: 1
    serviceMonitor:
      enabled: true
      metricsEndpoints:
        - port: metrics
          path: /metrics
          scheme: http
          interval: 20s
    ports:
      metrics:
        enabled: true

    config:
      receivers:
        kafka:
          brokers:
            - kafka-kafka-brokers.queuing.svc:9092
          topic: spans
          protocol_version: 3.3.0

      processors:
        batch:
          send_batch_size: 2048
          timeout: 1s
        memory_limiter:
          check_interval: 1s
          limit_percentage: 80
          spike_limit_percentage: 10

      exporters:
        logging:
          verbosity: detailed
          sampling_initial: 5
          sampling_thereafter: 20
        loadbalancing:
          protocol:
            otlp:
              tls:
                insecure: true
              sending_queue:
                num_consumers: 20
                queue_size: 10000
          resolver:
            dns:
              hostname: otel-processor-headless.trace-pipeline.svc
              port: 4320

      service:
        pipelines:
          traces:
            receivers:
              - kafka
            processors:
              - memory_limiter
              - batch
            exporters:
              - logging
              - loadbalancing
          metrics: null
          logs: null