
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: otel-distributor
  namespace: flux-system
spec:
  dependsOn:
    - name: kafka
  interval: 10m0s
  path: ./releases/otel-distributor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
