---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-weeder
  namespace: flux-system
spec:
  targetNamespace: monitoring
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
      version: 0.43.2
  interval: 10m0s
  values:
    mode: deployment
    fullnameOverride: "otel-weeder"
    config:
      receivers:
        prometheus: null
        zipkin: null

      processors:
        batch:
          send_batch_size: 10000
          timeout: 10s

      exporters:
        logging:
          logLevel: debug
        kafka:
          brokers:
            - kafka-kafka-brokers.queuing.svc:9092
          topic: otlp_spans
          protocol_version: 3.3.0

      service:
        pipelines:
          traces:
            receivers:
              - jaeger
              - otlp
            processors:
              - batch
            exporters:
              - logging
              - kafka
          metrics: null
          logs: null