---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
  interval: 10m0s
  values:
    loki:
      podLabels:
        generalized_service_type: observability
        generalized_service: loki



