---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  targetNamespace: logs
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.10.2
  interval: 10m0s
  values:
    fullnameOverride: loki
    loki:
      podLabels:
        service_category: telemetry
        signal_type: logs
        criticality: mid

      serviceMonitor:
        enabled: true
      tracing:
        jaegerAgentHost:  otel-ingester.trace-pipeline

      image:

