---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.9.10
  interval: 10m0s
  values:
    loki:
      podLabels:
        generalized_service_type: telemetry
        generalized_service: loki
      image:
        tag: 2.8.2
      serviceMonitor:
        enabled: true
      write:
        extraEnv:
  #        - name: JAEGER_AGENT_HOST
  #          value: tracing-tempo.tracing.svc
          - name: JAEGER_AGENT_HOST
            value: otel-ingester.trace-pipeline
          - name: JAEGER_SAMPLER_TYPE
            value: probabilistic
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
      read:
        extraEnv:
          - name: JAEGER_AGENT_HOST
            value: otel-ingester.trace-pipeline
          - name: JAEGER_SAMPLER_TYPE
            value: probabilistic
          - name: JAEGER_SAMPLER_PARAM
            value: "1"


