---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  targetNamespace: logging
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.9.10
  interval: 10m0s
  values:
    loki:
      podLabels:
        generalized_service_type: telemetry
        generalized_service: loki
      image:
        tag: 2.8.2
      serviceMonitor:
        enabled: true
      tracing:
        jaegerAgentHost:  otel-ingester.trace-pipeline



